Implement superagent's req.withCredentials() method
redfin/react-server pull request #935
Opened 2017-06-15 22:28 UTC by mlolson

https://github.com/redfin/react-server/issues/910

The [superagent implementation](https://github.com/visionmedia/superagent/blob/f5e39b7746268901c591dde08cd68a5e3944ced1/lib/request-base.js#L396), for reference.

2017-06-15 22:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/redfin/react-server?pullRequest=935) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/redfin/react-server?pullRequest=935) before we can accept your contribution.<br/><hr/>**Matt Olson** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/redfin/react-server?pullRequest=935) it.</sub>

2017-06-16 22:01 UTC, decoy31 requested changes

2017-06-16 22:01 UTC, decoy31 commented on packages/react-server/core/ReactServerAgent/Request.js
> +	if (on === undefined) {
Change this to: `if (typeof on === 'undefined')`.

2017-06-16 22:11 UTC, decoy31 commented on packages/react-server/core/ReactServerAgent/Request.js
> +	this._withCredentials = on;
If `this._withCredentials` is expected to be a boolean, I'd recommend changing this to: `this._withCredentials = !!on;`

2017-06-16 22:11 UTC, decoy31 commented on packages/react-server/core/ReactServerAgent/Request.js
> +	this._withCredentials = false;
To me, the property name `_withCredentials` is vague. One of/variant of the following would be more self-documenting:
- `_enableCORS`
- `_isCORSEnabled`
- `_corsEnabled`
- `_withCORSEnabled`
- `_withCrossOriginHTTPRequestsEnabled`

2017-06-18 20:11 UTC, mlolson commented on packages/react-server/core/ReactServerAgent/Request.js
> +	this._withCredentials = false;
I think it's best to stick with  the same syntax that [superagent uses](https://github.com/visionmedia/superagent/blob/f5e39b7746268901c591dde08cd68a5e3944ced1/lib/request-base.js#L396)

2017-06-19 18:10 UTC, decoy31 commented on packages/react-server/core/ReactServerAgent/Request.js
> +	this._withCredentials = false;
Oh right. I didn't notice we were modeling this after superagent. That's unfortunate.

2026-01-29 07:01 UTC, closed without merging